(function() {var implementors = {};
implementors['rusted_cypher'] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='struct' href='rusted_cypher/struct.Statement.html' title='rusted_cypher::Statement'>Statement</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='struct' href='rusted_cypher/cypher/result/struct.QueryResult.html' title='rusted_cypher::cypher::result::QueryResult'>QueryResult</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='struct' href='rusted_cypher/cypher/result/struct.RowResult.html' title='rusted_cypher::cypher::result::RowResult'>RowResult</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='struct' href='rusted_cypher/cypher/result/struct.CypherResult.html' title='rusted_cypher::cypher::result::CypherResult'>CypherResult</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='struct' href='rusted_cypher/error/struct.Neo4jError.html' title='rusted_cypher::error::Neo4jError'>Neo4jError</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='struct' href='rusted_cypher/error/struct.TimeParseError.html' title='rusted_cypher::error::TimeParseError'>TimeParseError</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html' title='core::fmt::Debug'>Debug</a> for <a class='enum' href='rusted_cypher/error/enum.GraphError.html' title='rusted_cypher::error::GraphError'>GraphError</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
